### ISSUE TITLE
> > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么

### ISSUE THREAD

**Issue by lumiran** [huawei-noah/DAFL#13]
> > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> > 会的 最好还是用1024的batch size

请问1024的batchsize需要多大的显存

_Originally posted by @tangjialiang-jj in https://github.com/huawei-noah/DAFL/issues/10#issuecomment-554932789_

我跑cifar10 两个1080ti就可

**Comment by tangjialiang-jj** [comment]
请问你用两块1080ti跑的时候还做了其他的并行化操作么，我用两块1080ti运行程序，最多把batchsize设置为256

**Comment by tangjialiang-jj** [comment]
请问你用两块1080ti跑的时候还做了其他的并行化操作么，我用两块1080ti运行程序，最多把batchsize设置为256

> > > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> > > 会的 最好还是用1024的batch size
> 
> 请问1024的batchsize需要多大的显存
> 
> _Originally posted by @tangjialiang-jj in [#10 (comment)](https://github.com/huawei-noah/DAFL/issues/10#issuecomment-554932789)_
> 
> 我跑cifar10 两个1080ti就可

请问你在用两块1080ti运行程序的时候是否还做了其他的操作，我用我的两块1080ti运行时batchsize最多设置为256
