### ISSUE TITLE
The "teacher" MNIST model has been successfully trained, but errors occurred while running "DAFL-train.py"r

### ISSUE THREAD

**Issue by QQ2737499951** [huawei-noah/DAFL#3]
The "teacher" model has been successfully trained, but errors occurred while running "DAFL-train.py",anybody know what's going on? Thank you！
============
![image](https://user-images.githubusercontent.com/33048209/64505557-d0ed7c00-d306-11e9-9cd9-64c29a14cfd8.png)
![image](https://user-images.githubusercontent.com/33048209/64505568-dd71d480-d306-11e9-9255-45384d20e0bf.png)

"D:\Program Files\Python368\python.exe" B:/PyTorch/DAFL/DAFL-train.py
[Epoch 0/200] [loss_oh: 0.306945] [loss_ie: -0.662719] [loss_a: -1.541127] [loss_kd: 1.733359]
[Epoch 0/200] [loss_oh: 0.391318] [loss_ie: -0.769967] [loss_a: -1.384207] [loss_kd: 1.527557]

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Program Files\Python368\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Program Files\Python368\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Program Files\Python368\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  **### File "B:\PyTorch\DAFL\DAFL-train.py", line 190, in <module>
    for i, (images, labels) in enumerate(data_test_loader):**
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\Program Files\Python368\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Program Files\Python368\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files\Python368\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Program Files\Python368\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files\Python368\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "D:\Program Files\Python368\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  **### File "B:/PyTorch/DAFL/DAFL-train.py", line 190, in <module>
    for i, (images, labels) in enumerate(data_test_loader):**
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "D:\Program Files\Python368\lib\site-packages\torch\utils\data\dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 16596) exited unexpectedly

进程已结束，退出代码 1

**Comment by HantingChen** [comment]
It seems that this problem is a pytorch issue when running on windows. You can reference: https://github.com/pytorch/pytorch/issues/5858.

**Comment by QQ2737499951** [comment]
> It seems that this problem is a pytorch issue when running on windows. You can reference: [pytorch/pytorch#5858](https://github.com/pytorch/pytorch/issues/5858).

==================
In Win10 environment, add the following code to solve the problem, thank you! In addition, you need to add a global acc_best。Thank you！

===============
if __name__ == '__main__':
    main()
================
"D:\Program Files\Python368\python.exe" B:/PyTorch/DAFL/DAFL-train.py
[Epoch 0/200] [loss_oh: 0.323446] [loss_ie: -0.723433] [loss_a: -1.377360] [loss_kd: 1.624475]
Test Avg. Loss: 0.014621, Accuracy: 0.711200
acc 0.7112 acc_best 0
[Epoch 1/200] [loss_oh: 0.398816] [loss_ie: -0.994161] [loss_a: -1.477517] [loss_kd: 0.681656]
Test Avg. Loss: 0.011073, Accuracy: 0.795800
acc 0.7958 acc_best 0.7112
[Epoch 2/200] [loss_oh: 0.694914] [loss_ie: -0.942158] [loss_a: -1.655259] [loss_kd: 0.491626]
Test Avg. Loss: 0.014511, Accuracy: 0.767200
acc 0.7672 acc_best 0.7958
[Epoch 3/200] [loss_oh: 0.372430] [loss_ie: -0.973961] [loss_a: -1.844167] [loss_kd: 0.325282]
Test Avg. Loss: 0.008011, Accuracy: 0.849000
acc 0.849 acc_best 0.7958
[Epoch 4/200] [loss_oh: 0.338971] [loss_ie: -0.982305] [loss_a: -1.716944] [loss_kd: 0.316894]
Test Avg. Loss: 0.006166, Accuracy: 0.877000
acc 0.877 acc_best 0.849
[Epoch 5/200] [loss_oh: 0.322520] [loss_ie: -0.983168] [loss_a: -1.626730] [loss_kd: 0.278169]
Test Avg. Loss: 0.005701, Accuracy: 0.884200
acc 0.8842 acc_best 0.877
[Epoch 6/200] [loss_oh: 0.296399] [loss_ie: -0.980377] [loss_a: -1.993171] [loss_kd: 0.276820]
Test Avg. Loss: 0.005980, Accuracy: 0.880800
acc 0.8808 acc_best 0.8842
[Epoch 7/200] [loss_oh: 0.310579] [loss_ie: -0.989021] [loss_a: -1.786998] [loss_kd: 0.218293]
Test Avg. Loss: 0.004707, Accuracy: 0.903100
acc 0.9031 acc_best 0.8842
[Epoch 8/200] [loss_oh: 0.324671] [loss_ie: -0.970958] [loss_a: -1.733145] [loss_kd: 0.288907]
Test Avg. Loss: 0.005629, Accuracy: 0.881200
acc 0.8812 acc_best 0.9031
[Epoch 9/200] [loss_oh: 0.370372] [loss_ie: -0.934299] [loss_a: -1.562675] [loss_kd: 0.252697]
Test Avg. Loss: 0.018975, Accuracy: 0.697800
acc 0.6978 acc_best 0.9031
[Epoch 10/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 11/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 12/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 13/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 14/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 15/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 16/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
[Epoch 17/200] [loss_oh: 1.752401] [loss_ie: -0.963753] [loss_a: -0.129881] [loss_kd: 0.000000]
Test Avg. Loss: 0.018973, Accuracy: 0.698000
acc 0.698 acc_best 0.9031
