### ISSUE TITLE
训练CIFAR-10，如果调小batch，lr怎样调节合适？

### ISSUE THREAD

**Issue by alwayslj** [huawei-noah/DAFL#8]
accuracy一直在50%左右

**Comment by HantingChen** [comment]
请问batch size调整为多少了？
调整batch size以后可能还需要调整每个超参数（oh ie a）

**Comment by alwayslj** [comment]
> 请问batch size调整为多少了？
> 调整batch size以后可能还需要调整每个超参数（oh ie a）
感谢您的回复！受限于计算资源，batch size调整为了64，虽然教师网络训练的很好，但是在DAFL-train的时候，accuracy一直在50徘徊。如果调整超参数的话，有什么trick吗

**Comment by HantingChen** [comment]
> > 请问batch size调整为多少了？
> > 调整batch size以后可能还需要调整每个超参数（oh ie a）
> > 感谢您的回复！受限于计算资源，batch size调整为了64，虽然教师网络训练的很好，但是在DAFL-train的时候，accuracy一直在50徘徊。如果调整超参数的话，有什么trick吗

batch size太小可能对准确率有影响，或许可以尝试用更小的teacher和student网络（比如直接减少channel数为1/2、1/4），这样可以不用再调整超参。
